### PR TITLE
Fix Token Update Logic and JWT Handling

### PR DESCRIPTION
**Pull request by Remma27**
No estaba en la historia de usuario pero fue un error que surgio despues de los merge.

### CODE REVIEW

**Comment by Remma27** [comment]
post login

Login funcionando correctamente, además, cambios para validar el email del current user.

**Comment by LilMat69** [comment]
Can you please attach a brief description of what you did, since there is no US, just to be clear about it, sorry for the inconvenience >:)

**Comment by Remma27** [comment]
This PR introduces several changes to enhance JWT handling and token management. Here are the main updates:

JWT Enhancements:
Updated generate_jwt to include user id and email in the JWT payload in addition to the role. This change ensures that the JWT now carries more comprehensive user information, which is necessary for validation processes in various endpoints. Modified the validate_jwt function to return additional details (rolName and email) from the JWT payload. This enhancement allows for more robust user validation.

User Model:
Refined the update_token method in the UserModel to address issues with token updates. Previously, the method would display an error message even when the token was updated correctly. The current implementation improves error handling and ensures the token update is accurately reflected in the database.

Authorization Handling:
Adjusted the verify_auth controller to check for the presence of a token and validate its correctness. The controller now correctly handles cases where the token is missing or invalid, providing appropriate responses.

Token Update in Database:
Updated the database token update logic to avoid errors related to matched_count. This ensures that the token is only updated when a valid user is found, improving reliability.

These changes aim to improve the security and reliability of user authentication and authorization processes, ensuring that only the appropriate users can perform actions like deleting LostObject entries based on their credentials.

**Review by LilMat69 — APPROVED** [review]
All good

**Pull request merged**
